# Generated by Django 4.0.5 on 2022-06-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='post_text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='post_title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Created_date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Published_date',
        ),
    ]
